# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

server_report:
  url: /servers/:hash/report
  param: { module: servers, action: report }
    
server:
  class: sfPropelORMRouteCollection
  options:
    model:                Server
    module:               server
    prefix_path:          /server
    column:               id
    with_wildcard_routes: true
    object_actions: { verUltimoReporte: get }

# default rules
homepage:
  url:   /
  param: { module: server, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
