# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Gestor Distribuido EVEA Chubut
    description:  Gestión de la Plataforma Distribuida EVEA Chubut
    #keywords:     symfony, project
    language:     es
    #robots:       index, follow
    viewport:     "width=device-width, initial-scale=1"

  stylesheets:    [main.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
